disabled:
    - concat_without_spaces
    - laravel_phpdoc_separation
enabled:
    - concat_with_spaces
    - phpdoc_separation
    - phpdoc_summary
finder:
    exclude:
        - 'node_modules'
        - 'storage'
        - 'vendor'
    name: '*.php'
    not-name:
        - '*.blade.php'
        - '_ide_helper.php'
monolithic: true
preset: laravel
risky: false
version: 8.2
