/**
 * Stop!
 * 
 * This is a generated file. It should be regenerated whenever
 * the lucide dependency is updated.
 *
 * https://lucide.dev/
 */

import {
  Activity,
  Airplay,
  AlarmCheck,
  AlarmClock,
  AlarmClockOff,
  AlarmMinus,
  AlarmPlus,
  Album,
  AlertCircle,
  AlertOctagon,
  AlertTriangle,
  AlignCenter,
  AlignCenterHorizontal,
  AlignCenterVertical,
  AlignEndHorizontal,
  AlignEndVertical,
  AlignHorizonalDistributeCenter,
  AlignHorizonalDistributeEnd,
  AlignHorizonalDistributeStart,
  AlignHorizontalJustifyCenter,
  AlignHorizontalJustifyEnd,
  AlignHorizontalJustifyStart,
  AlignHorizontalSpaceAround,
  AlignHorizontalSpaceBetween,
  AlignJustify,
  AlignLeft,
  AlignRight,
  AlignStartHorizontal,
  AlignStartVertical,
  AlignVerticalDistributeCenter,
  AlignVerticalDistributeEnd,
  AlignVerticalDistributeStart,
  AlignVerticalJustifyCenter,
  AlignVerticalJustifyEnd,
  AlignVerticalJustifyStart,
  AlignVerticalSpaceAround,
  AlignVerticalSpaceBetween,
  Anchor,
  Aperture,
  Archive,
  ArrowBigDown,
  ArrowBigLeft,
  ArrowBigRight,
  ArrowBigUp,
  ArrowDown,
  ArrowDownCircle,
  ArrowDownLeft,
  ArrowDownRight,
  ArrowLeft,
  ArrowLeftCircle,
  ArrowLeftRight,
  ArrowRight,
  ArrowRightCircle,
  ArrowUp,
  ArrowUpCircle,
  ArrowUpLeft,
  ArrowUpRight,
  Asterisk,
  AtSign,
  Award,
  Axe,
  Banknote,
  BarChart,
  BarChart2,
  Baseline,
  Battery,
  BatteryCharging,
  BatteryFull,
  BatteryLow,
  BatteryMedium,
  Beaker,
  Bell,
  BellMinus,
  BellOff,
  BellPlus,
  BellRing,
  Bike,
  Binary,
  Bitcoin,
  Bluetooth,
  BluetoothConnected,
  BluetoothOff,
  BluetoothSearching,
  Bold,
  Book,
  BookOpen,
  Bookmark,
  BookmarkMinus,
  BookmarkPlus,
  Bot,
  Box,
  BoxSelect,
  Briefcase,
  Brush,
  Bug,
  Building,
  Bus,
  Calculator,
  Calendar,
  Camera,
  CameraOff,
  Car,
  Carrot,
  Cast,
  Check,
  CheckCircle,
  CheckCircle2,
  CheckSquare,
  ChevronDown,
  ChevronFirst,
  ChevronLast,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsDown,
  ChevronsDownUp,
  ChevronsLeft,
  ChevronsRight,
  ChevronsUp,
  ChevronsUpDown,
  Chrome,
  Circle,
  CircleSlashed,
  Clipboard,
  ClipboardCheck,
  ClipboardCopy,
  ClipboardList,
  ClipboardX,
  Clock,
  Clock1,
  Clock10,
  Clock11,
  Clock12,
  Clock2,
  Clock3,
  Clock4,
  Clock5,
  Clock6,
  Clock7,
  Clock8,
  Clock9,
  Cloud,
  CloudDrizzle,
  CloudFog,
  CloudHail,
  CloudLightning,
  CloudMoon,
  CloudOff,
  CloudRain,
  CloudRainWind,
  CloudSnow,
  CloudSun,
  Cloudy,
  Clover,
  Code,
  Code2,
  Codepen,
  Codesandbox,
  Coffee,
  Coins,
  Columns,
  Command,
  Compass,
  Contact,
  Contrast,
  Cookie,
  Copy,
  Copyleft,
  Copyright,
  CornerDownLeft,
  CornerDownRight,
  CornerLeftDown,
  CornerLeftUp,
  CornerRightDown,
  CornerRightUp,
  CornerUpLeft,
  CornerUpRight,
  Cpu,
  CreditCard,
  Crop,
  Cross,
  Crosshair,
  Crown,
  Currency,
  Database,
  Delete,
  Disc,
  Divide,
  DivideCircle,
  DivideSquare,
  DollarSign,
  Download,
  DownloadCloud,
  Dribbble,
  Droplet,
  Droplets,
  Drumstick,
  Edit,
  Edit2,
  Edit3,
  Egg,
  Equal,
  EqualNot,
  Euro,
  Expand,
  ExternalLink,
  Eye,
  EyeOff,
  Facebook,
  FastForward,
  Feather,
  Figma,
  File,
  FileCheck,
  FileCheck2,
  FileCode,
  FileDigit,
  FileInput,
  FileMinus,
  FileMinus2,
  FileOutput,
  FilePlus,
  FilePlus2,
  FileSearch,
  FileText,
  FileX,
  FileX2,
  Files,
  Film,
  Filter,
  Flag,
  FlagTriangleLeft,
  FlagTriangleRight,
  Flame,
  Flashlight,
  FlashlightOff,
  FlaskConical,
  FlaskRound,
  Folder,
  FolderMinus,
  FolderOpen,
  FolderPlus,
  FormInput,
  Forward,
  Framer,
  Frown,
  FunctionSquare,
  Gamepad,
  Gamepad2,
  Gauge,
  Gavel,
  Gem,
  Ghost,
  Gift,
  GitBranch,
  GitBranchPlus,
  GitCommit,
  GitMerge,
  GitPullRequest,
  Github,
  Gitlab,
  Glasses,
  Globe,
  Globe2,
  Grab,
  GraduationCap,
  Grid,
  GripHorizontal,
  GripVertical,
  Hammer,
  Hand,
  HandMetal,
  HardDrive,
  HardHat,
  Hash,
  Haze,
  Headphones,
  Heart,
  HelpCircle,
  Hexagon,
  Highlighter,
  History,
  Home,
  Image,
  ImageMinus,
  ImageOff,
  ImagePlus,
  Import,
  Inbox,
  Indent,
  IndianRupee,
  Infinity,
  Info,
  Inspect,
  Instagram,
  Italic,
  JapaneseYen,
  Key,
  Keyboard,
  Landmark,
  Languages,
  Laptop,
  Laptop2,
  Lasso,
  LassoSelect,
  Layers,
  Layout,
  LayoutDashboard,
  LayoutGrid,
  LayoutList,
  LayoutTemplate,
  Library,
  LifeBuoy,
  Lightbulb,
  LightbulbOff,
  Link,
  Link2,
  Link2Off,
  Linkedin,
  List,
  ListChecks,
  ListMinus,
  ListOrdered,
  ListPlus,
  ListX,
  Loader,
  Loader2,
  Locate,
  LocateFixed,
  LocateOff,
  Lock,
  LogIn,
  LogOut,
  Mail,
  Map,
  MapPin,
  Maximize,
  Maximize2,
  Megaphone,
  Meh,
  Menu,
  MessageCircle,
  MessageSquare,
  Mic,
  MicOff,
  Minimize,
  Minimize2,
  Minus,
  MinusCircle,
  MinusSquare,
  Monitor,
  MonitorOff,
  MonitorSpeaker,
  Moon,
  MoreHorizontal,
  MoreVertical,
  Mountain,
  MountainSnow,
  MousePointer,
  MousePointer2,
  MousePointerClick,
  Move,
  MoveDiagonal,
  MoveDiagonal2,
  MoveHorizontal,
  MoveVertical,
  Music,
  Navigation,
  Navigation2,
  Network,
  Octagon,
  Option,
  Outdent,
  Package,
  PackageCheck,
  PackageMinus,
  PackagePlus,
  PackageSearch,
  PackageX,
  Palette,
  Palmtree,
  Paperclip,
  Pause,
  PauseCircle,
  PauseOctagon,
  PenTool,
  Pencil,
  Percent,
  PersonStanding,
  Phone,
  PhoneCall,
  PhoneForwarded,
  PhoneIncoming,
  PhoneMissed,
  PhoneOff,
  PhoneOutgoing,
  PieChart,
  PiggyBank,
  Pin,
  Pipette,
  Plane,
  Play,
  PlayCircle,
  PlugZap,
  Plus,
  PlusCircle,
  PlusSquare,
  Pocket,
  Podcast,
  Pointer,
  PoundSterling,
  Power,
  PowerOff,
  Printer,
  QrCode,
  Quote,
  Radio,
  RadioReceiver,
  Redo,
  RefreshCcw,
  RefreshCw,
  Regex,
  Repeat,
  Repeat1,
  Reply,
  ReplyAll,
  Rewind,
  RockingChair,
  RotateCcw,
  RotateCw,
  Rss,
  Ruler,
  RussianRuble,
  Save,
  Scale,
  Scan,
  ScanLine,
  Scissors,
  ScreenShare,
  ScreenShareOff,
  Search,
  Send,
  SeparatorHorizontal,
  SeparatorVertical,
  Server,
  ServerCrash,
  ServerOff,
  Settings,
  Settings2,
  Share,
  Share2,
  Sheet,
  Shield,
  ShieldAlert,
  ShieldCheck,
  ShieldClose,
  ShieldOff,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Shovel,
  Shrink,
  Shuffle,
  Sidebar,
  SidebarClose,
  SidebarOpen,
  Sigma,
  Signal,
  SignalHigh,
  SignalLow,
  SignalMedium,
  SignalZero,
  SkipBack,
  SkipForward,
  Skull,
  Slack,
  Slash,
  Sliders,
  Smartphone,
  SmartphoneCharging,
  Smile,
  Snowflake,
  SortAsc,
  SortDesc,
  Speaker,
  Sprout,
  Square,
  Star,
  StarHalf,
  StopCircle,
  StretchHorizontal,
  StretchVertical,
  Strikethrough,
  Subscript,
  Sun,
  Sunrise,
  Sunset,
  Superscript,
  SwissFranc,
  SwitchCamera,
  Table,
  Tablet,
  Tag,
  Target,
  Tent,
  Terminal,
  TerminalSquare,
  TextCursor,
  TextCursorInput,
  Thermometer,
  ThermometerSnowflake,
  ThermometerSun,
  ThumbsDown,
  ThumbsUp,
  Ticket,
  Timer,
  TimerOff,
  TimerReset,
  ToggleLeft,
  ToggleRight,
  Tornado,
  Trash,
  Trash2,
  Trello,
  TrendingDown,
  TrendingUp,
  Triangle,
  Truck,
  Tv,
  Tv2,
  Twitch,
  Twitter,
  Type,
  Umbrella,
  Underline,
  Undo,
  Unlink,
  Unlink2,
  Unlock,
  Upload,
  UploadCloud,
  User,
  UserCheck,
  UserMinus,
  UserPlus,
  UserX,
  Users,
  Verified,
  Vibrate,
  Video,
  VideoOff,
  View,
  Voicemail,
  Volume,
  Volume1,
  Volume2,
  VolumeX,
  Wallet,
  Wand,
  Watch,
  Waves,
  Webcam,
  Wifi,
  WifiOff,
  Wind,
  WrapText,
  Wrench,
  X,
  XCircle,
  XOctagon,
  XSquare,
  Youtube,
  Zap,
  ZapOff,
  ZoomIn,
  ZoomOut,
} from 'lucide'

/**
 * Icon map
 */
export const icons = {
  'activity': Activity,
  'airplay': Airplay,
  'alarm-check': AlarmCheck,
  'alarm-clock': AlarmClock,
  'alarm-clock-off': AlarmClockOff,
  'alarm-minus': AlarmMinus,
  'alarm-plus': AlarmPlus,
  'album': Album,
  'alert-circle': AlertCircle,
  'alert-octagon': AlertOctagon,
  'alert-triangle': AlertTriangle,
  'align-center': AlignCenter,
  'align-center-horizontal': AlignCenterHorizontal,
  'align-center-vertical': AlignCenterVertical,
  'align-end-horizontal': AlignEndHorizontal,
  'align-end-vertical': AlignEndVertical,
  'align-horizonal-distribute-center': AlignHorizonalDistributeCenter,
  'align-horizonal-distribute-end': AlignHorizonalDistributeEnd,
  'align-horizonal-distribute-start': AlignHorizonalDistributeStart,
  'align-horizontal-justify-center': AlignHorizontalJustifyCenter,
  'align-horizontal-justify-end': AlignHorizontalJustifyEnd,
  'align-horizontal-justify-start': AlignHorizontalJustifyStart,
  'align-horizontal-space-around': AlignHorizontalSpaceAround,
  'align-horizontal-space-between': AlignHorizontalSpaceBetween,
  'align-justify': AlignJustify,
  'align-left': AlignLeft,
  'align-right': AlignRight,
  'align-start-horizontal': AlignStartHorizontal,
  'align-start-vertical': AlignStartVertical,
  'align-vertical-distribute-center': AlignVerticalDistributeCenter,
  'align-vertical-distribute-end': AlignVerticalDistributeEnd,
  'align-vertical-distribute-start': AlignVerticalDistributeStart,
  'align-vertical-justify-center': AlignVerticalJustifyCenter,
  'align-vertical-justify-end': AlignVerticalJustifyEnd,
  'align-vertical-justify-start': AlignVerticalJustifyStart,
  'align-vertical-space-around': AlignVerticalSpaceAround,
  'align-vertical-space-between': AlignVerticalSpaceBetween,
  'anchor': Anchor,
  'aperture': Aperture,
  'archive': Archive,
  'arrow-big-down': ArrowBigDown,
  'arrow-big-left': ArrowBigLeft,
  'arrow-big-right': ArrowBigRight,
  'arrow-big-up': ArrowBigUp,
  'arrow-down': ArrowDown,
  'arrow-down-circle': ArrowDownCircle,
  'arrow-down-left': ArrowDownLeft,
  'arrow-down-right': ArrowDownRight,
  'arrow-left': ArrowLeft,
  'arrow-left-circle': ArrowLeftCircle,
  'arrow-left-right': ArrowLeftRight,
  'arrow-right': ArrowRight,
  'arrow-right-circle': ArrowRightCircle,
  'arrow-up': ArrowUp,
  'arrow-up-circle': ArrowUpCircle,
  'arrow-up-left': ArrowUpLeft,
  'arrow-up-right': ArrowUpRight,
  'asterisk': Asterisk,
  'at-sign': AtSign,
  'award': Award,
  'axe': Axe,
  'banknote': Banknote,
  'bar-chart': BarChart,
  'bar-chart-2': BarChart2,
  'baseline': Baseline,
  'battery': Battery,
  'battery-charging': BatteryCharging,
  'battery-full': BatteryFull,
  'battery-low': BatteryLow,
  'battery-medium': BatteryMedium,
  'beaker': Beaker,
  'bell': Bell,
  'bell-minus': BellMinus,
  'bell-off': BellOff,
  'bell-plus': BellPlus,
  'bell-ring': BellRing,
  'bike': Bike,
  'binary': Binary,
  'bitcoin': Bitcoin,
  'bluetooth': Bluetooth,
  'bluetooth-connected': BluetoothConnected,
  'bluetooth-off': BluetoothOff,
  'bluetooth-searching': BluetoothSearching,
  'bold': Bold,
  'book': Book,
  'book-open': BookOpen,
  'bookmark': Bookmark,
  'bookmark-minus': BookmarkMinus,
  'bookmark-plus': BookmarkPlus,
  'bot': Bot,
  'box': Box,
  'box-select': BoxSelect,
  'briefcase': Briefcase,
  'brush': Brush,
  'bug': Bug,
  'building': Building,
  'bus': Bus,
  'calculator': Calculator,
  'calendar': Calendar,
  'camera': Camera,
  'camera-off': CameraOff,
  'car': Car,
  'carrot': Carrot,
  'cast': Cast,
  'check': Check,
  'check-circle': CheckCircle,
  'check-circle-2': CheckCircle2,
  'check-square': CheckSquare,
  'chevron-down': ChevronDown,
  'chevron-first': ChevronFirst,
  'chevron-last': ChevronLast,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevron-up': ChevronUp,
  'chevrons-down': ChevronsDown,
  'chevrons-down-up': ChevronsDownUp,
  'chevrons-left': ChevronsLeft,
  'chevrons-right': ChevronsRight,
  'chevrons-up': ChevronsUp,
  'chevrons-up-down': ChevronsUpDown,
  'chrome': Chrome,
  'circle': Circle,
  'circle-slashed': CircleSlashed,
  'clipboard': Clipboard,
  'clipboard-check': ClipboardCheck,
  'clipboard-copy': ClipboardCopy,
  'clipboard-list': ClipboardList,
  'clipboard-x': ClipboardX,
  'clock': Clock,
  'clock-1': Clock1,
  'clock-10': Clock10,
  'clock-11': Clock11,
  'clock-12': Clock12,
  'clock-2': Clock2,
  'clock-3': Clock3,
  'clock-4': Clock4,
  'clock-5': Clock5,
  'clock-6': Clock6,
  'clock-7': Clock7,
  'clock-8': Clock8,
  'clock-9': Clock9,
  'cloud': Cloud,
  'cloud-drizzle': CloudDrizzle,
  'cloud-fog': CloudFog,
  'cloud-hail': CloudHail,
  'cloud-lightning': CloudLightning,
  'cloud-moon': CloudMoon,
  'cloud-off': CloudOff,
  'cloud-rain': CloudRain,
  'cloud-rain-wind': CloudRainWind,
  'cloud-snow': CloudSnow,
  'cloud-sun': CloudSun,
  'cloudy': Cloudy,
  'clover': Clover,
  'code': Code,
  'code-2': Code2,
  'codepen': Codepen,
  'codesandbox': Codesandbox,
  'coffee': Coffee,
  'coins': Coins,
  'columns': Columns,
  'command': Command,
  'compass': Compass,
  'contact': Contact,
  'contrast': Contrast,
  'cookie': Cookie,
  'copy': Copy,
  'copyleft': Copyleft,
  'copyright': Copyright,
  'corner-down-left': CornerDownLeft,
  'corner-down-right': CornerDownRight,
  'corner-left-down': CornerLeftDown,
  'corner-left-up': CornerLeftUp,
  'corner-right-down': CornerRightDown,
  'corner-right-up': CornerRightUp,
  'corner-up-left': CornerUpLeft,
  'corner-up-right': CornerUpRight,
  'cpu': Cpu,
  'credit-card': CreditCard,
  'crop': Crop,
  'cross': Cross,
  'crosshair': Crosshair,
  'crown': Crown,
  'currency': Currency,
  'database': Database,
  'delete': Delete,
  'disc': Disc,
  'divide': Divide,
  'divide-circle': DivideCircle,
  'divide-square': DivideSquare,
  'dollar-sign': DollarSign,
  'download': Download,
  'download-cloud': DownloadCloud,
  'dribbble': Dribbble,
  'droplet': Droplet,
  'droplets': Droplets,
  'drumstick': Drumstick,
  'edit': Edit,
  'edit-2': Edit2,
  'edit-3': Edit3,
  'egg': Egg,
  'equal': Equal,
  'equal-not': EqualNot,
  'euro': Euro,
  'expand': Expand,
  'external-link': ExternalLink,
  'eye': Eye,
  'eye-off': EyeOff,
  'facebook': Facebook,
  'fast-forward': FastForward,
  'feather': Feather,
  'figma': Figma,
  'file': File,
  'file-check': FileCheck,
  'file-check-2': FileCheck2,
  'file-code': FileCode,
  'file-digit': FileDigit,
  'file-input': FileInput,
  'file-minus': FileMinus,
  'file-minus-2': FileMinus2,
  'file-output': FileOutput,
  'file-plus': FilePlus,
  'file-plus-2': FilePlus2,
  'file-search': FileSearch,
  'file-text': FileText,
  'file-x': FileX,
  'file-x2': FileX2,
  'files': Files,
  'film': Film,
  'filter': Filter,
  'flag': Flag,
  'flag-triangle-left': FlagTriangleLeft,
  'flag-triangle-right': FlagTriangleRight,
  'flame': Flame,
  'flashlight': Flashlight,
  'flashlight-off': FlashlightOff,
  'flask-conical': FlaskConical,
  'flask-round': FlaskRound,
  'folder': Folder,
  'folder-minus': FolderMinus,
  'folder-open': FolderOpen,
  'folder-plus': FolderPlus,
  'form-input': FormInput,
  'forward': Forward,
  'framer': Framer,
  'frown': Frown,
  'function-square': FunctionSquare,
  'gamepad': Gamepad,
  'gamepad-2': Gamepad2,
  'gauge': Gauge,
  'gavel': Gavel,
  'gem': Gem,
  'ghost': Ghost,
  'gift': Gift,
  'git-branch': GitBranch,
  'git-branch-plus': GitBranchPlus,
  'git-commit': GitCommit,
  'git-merge': GitMerge,
  'git-pull-request': GitPullRequest,
  'github': Github,
  'gitlab': Gitlab,
  'glasses': Glasses,
  'globe': Globe,
  'globe-2': Globe2,
  'grab': Grab,
  'graduation-cap': GraduationCap,
  'grid': Grid,
  'grip-horizontal': GripHorizontal,
  'grip-vertical': GripVertical,
  'hammer': Hammer,
  'hand': Hand,
  'hand-metal': HandMetal,
  'hard-drive': HardDrive,
  'hard-hat': HardHat,
  'hash': Hash,
  'haze': Haze,
  'headphones': Headphones,
  'heart': Heart,
  'help-circle': HelpCircle,
  'hexagon': Hexagon,
  'highlighter': Highlighter,
  'history': History,
  'home': Home,
  'image': Image,
  'image-minus': ImageMinus,
  'image-off': ImageOff,
  'image-plus': ImagePlus,
  'import': Import,
  'inbox': Inbox,
  'indent': Indent,
  'indian-rupee': IndianRupee,
  'infinity': Infinity,
  'info': Info,
  'inspect': Inspect,
  'instagram': Instagram,
  'italic': Italic,
  'japanese-yen': JapaneseYen,
  'key': Key,
  'keyboard': Keyboard,
  'landmark': Landmark,
  'languages': Languages,
  'laptop': Laptop,
  'laptop-2': Laptop2,
  'lasso': Lasso,
  'lasso-select': LassoSelect,
  'layers': Layers,
  'layout': Layout,
  'layout-dashboard': LayoutDashboard,
  'layout-grid': LayoutGrid,
  'layout-list': LayoutList,
  'layout-template': LayoutTemplate,
  'library': Library,
  'life-buoy': LifeBuoy,
  'lightbulb': Lightbulb,
  'lightbulb-off': LightbulbOff,
  'link': Link,
  'link-2': Link2,
  'link-2off': Link2Off,
  'linkedin': Linkedin,
  'list': List,
  'list-checks': ListChecks,
  'list-minus': ListMinus,
  'list-ordered': ListOrdered,
  'list-plus': ListPlus,
  'list-x': ListX,
  'loader': Loader,
  'loader-2': Loader2,
  'locate': Locate,
  'locate-fixed': LocateFixed,
  'locate-off': LocateOff,
  'lock': Lock,
  'log-in': LogIn,
  'log-out': LogOut,
  'mail': Mail,
  'map': Map,
  'map-pin': MapPin,
  'maximize': Maximize,
  'maximize-2': Maximize2,
  'megaphone': Megaphone,
  'meh': Meh,
  'menu': Menu,
  'message-circle': MessageCircle,
  'message-square': MessageSquare,
  'mic': Mic,
  'mic-off': MicOff,
  'minimize': Minimize,
  'minimize-2': Minimize2,
  'minus': Minus,
  'minus-circle': MinusCircle,
  'minus-square': MinusSquare,
  'monitor': Monitor,
  'monitor-off': MonitorOff,
  'monitor-speaker': MonitorSpeaker,
  'moon': Moon,
  'more-horizontal': MoreHorizontal,
  'more-vertical': MoreVertical,
  'mountain': Mountain,
  'mountain-snow': MountainSnow,
  'mouse-pointer': MousePointer,
  'mouse-pointer-2': MousePointer2,
  'mouse-pointer-click': MousePointerClick,
  'move': Move,
  'move-diagonal': MoveDiagonal,
  'move-diagonal-2': MoveDiagonal2,
  'move-horizontal': MoveHorizontal,
  'move-vertical': MoveVertical,
  'music': Music,
  'navigation': Navigation,
  'navigation-2': Navigation2,
  'network': Network,
  'octagon': Octagon,
  'option': Option,
  'outdent': Outdent,
  'package': Package,
  'package-check': PackageCheck,
  'package-minus': PackageMinus,
  'package-plus': PackagePlus,
  'package-search': PackageSearch,
  'package-x': PackageX,
  'palette': Palette,
  'palmtree': Palmtree,
  'paperclip': Paperclip,
  'pause': Pause,
  'pause-circle': PauseCircle,
  'pause-octagon': PauseOctagon,
  'pen-tool': PenTool,
  'pencil': Pencil,
  'percent': Percent,
  'person-standing': PersonStanding,
  'phone': Phone,
  'phone-call': PhoneCall,
  'phone-forwarded': PhoneForwarded,
  'phone-incoming': PhoneIncoming,
  'phone-missed': PhoneMissed,
  'phone-off': PhoneOff,
  'phone-outgoing': PhoneOutgoing,
  'pie-chart': PieChart,
  'piggy-bank': PiggyBank,
  'pin': Pin,
  'pipette': Pipette,
  'plane': Plane,
  'play': Play,
  'play-circle': PlayCircle,
  'plug-zap': PlugZap,
  'plus': Plus,
  'plus-circle': PlusCircle,
  'plus-square': PlusSquare,
  'pocket': Pocket,
  'podcast': Podcast,
  'pointer': Pointer,
  'pound-sterling': PoundSterling,
  'power': Power,
  'power-off': PowerOff,
  'printer': Printer,
  'qr-code': QrCode,
  'quote': Quote,
  'radio': Radio,
  'radio-receiver': RadioReceiver,
  'redo': Redo,
  'refresh-ccw': RefreshCcw,
  'refresh-cw': RefreshCw,
  'regex': Regex,
  'repeat': Repeat,
  'repeat-1': Repeat1,
  'reply': Reply,
  'reply-all': ReplyAll,
  'rewind': Rewind,
  'rocking-chair': RockingChair,
  'rotate-ccw': RotateCcw,
  'rotate-cw': RotateCw,
  'rss': Rss,
  'ruler': Ruler,
  'russian-ruble': RussianRuble,
  'save': Save,
  'scale': Scale,
  'scan': Scan,
  'scan-line': ScanLine,
  'scissors': Scissors,
  'screen-share': ScreenShare,
  'screen-share-off': ScreenShareOff,
  'search': Search,
  'send': Send,
  'separator-horizontal': SeparatorHorizontal,
  'separator-vertical': SeparatorVertical,
  'server': Server,
  'server-crash': ServerCrash,
  'server-off': ServerOff,
  'settings': Settings,
  'settings-2': Settings2,
  'share': Share,
  'share-2': Share2,
  'sheet': Sheet,
  'shield': Shield,
  'shield-alert': ShieldAlert,
  'shield-check': ShieldCheck,
  'shield-close': ShieldClose,
  'shield-off': ShieldOff,
  'shirt': Shirt,
  'shopping-bag': ShoppingBag,
  'shopping-cart': ShoppingCart,
  'shovel': Shovel,
  'shrink': Shrink,
  'shuffle': Shuffle,
  'sidebar': Sidebar,
  'sidebar-close': SidebarClose,
  'sidebar-open': SidebarOpen,
  'sigma': Sigma,
  'signal': Signal,
  'signal-high': SignalHigh,
  'signal-low': SignalLow,
  'signal-medium': SignalMedium,
  'signal-zero': SignalZero,
  'skip-back': SkipBack,
  'skip-forward': SkipForward,
  'skull': Skull,
  'slack': Slack,
  'slash': Slash,
  'sliders': Sliders,
  'smartphone': Smartphone,
  'smartphone-charging': SmartphoneCharging,
  'smile': Smile,
  'snowflake': Snowflake,
  'sort-asc': SortAsc,
  'sort-desc': SortDesc,
  'speaker': Speaker,
  'sprout': Sprout,
  'square': Square,
  'star': Star,
  'star-half': StarHalf,
  'stop-circle': StopCircle,
  'stretch-horizontal': StretchHorizontal,
  'stretch-vertical': StretchVertical,
  'strikethrough': Strikethrough,
  'subscript': Subscript,
  'sun': Sun,
  'sunrise': Sunrise,
  'sunset': Sunset,
  'superscript': Superscript,
  'swiss-franc': SwissFranc,
  'switch-camera': SwitchCamera,
  'table': Table,
  'tablet': Tablet,
  'tag': Tag,
  'target': Target,
  'tent': Tent,
  'terminal': Terminal,
  'terminal-square': TerminalSquare,
  'text-cursor': TextCursor,
  'text-cursor-input': TextCursorInput,
  'thermometer': Thermometer,
  'thermometer-snowflake': ThermometerSnowflake,
  'thermometer-sun': ThermometerSun,
  'thumbs-down': ThumbsDown,
  'thumbs-up': ThumbsUp,
  'ticket': Ticket,
  'timer': Timer,
  'timer-off': TimerOff,
  'timer-reset': TimerReset,
  'toggle-left': ToggleLeft,
  'toggle-right': ToggleRight,
  'tornado': Tornado,
  'trash': Trash,
  'trash-2': Trash2,
  'trello': Trello,
  'trending-down': TrendingDown,
  'trending-up': TrendingUp,
  'triangle': Triangle,
  'truck': Truck,
  'tv': Tv,
  'tv-2': Tv2,
  'twitch': Twitch,
  'twitter': Twitter,
  'type': Type,
  'umbrella': Umbrella,
  'underline': Underline,
  'undo': Undo,
  'unlink': Unlink,
  'unlink-2': Unlink2,
  'unlock': Unlock,
  'upload': Upload,
  'upload-cloud': UploadCloud,
  'user': User,
  'user-check': UserCheck,
  'user-minus': UserMinus,
  'user-plus': UserPlus,
  'user-x': UserX,
  'users': Users,
  'verified': Verified,
  'vibrate': Vibrate,
  'video': Video,
  'video-off': VideoOff,
  'view': View,
  'voicemail': Voicemail,
  'volume': Volume,
  'volume-1': Volume1,
  'volume-2': Volume2,
  'volume-x': VolumeX,
  'wallet': Wallet,
  'wand': Wand,
  'watch': Watch,
  'waves': Waves,
  'webcam': Webcam,
  'wifi': Wifi,
  'wifi-off': WifiOff,
  'wind': Wind,
  'wrap-text': WrapText,
  'wrench': Wrench,
  'x': X,
  'x-circle': XCircle,
  'x-octagon': XOctagon,
  'x-square': XSquare,
  'youtube': Youtube,
  'zap': Zap,
  'zap-off': ZapOff,
  'zoom-in': ZoomIn,
  'zoom-out': ZoomOut,
}

/**
 * Icon name
 */
export type IconName = keyof typeof icons
