<{{ $el }} @class([
    $class => true,
    'block' => $block,
    'flex' => !$block && !$grid,
    'gap-6' => $gap,    
    'grid' => $grid,
    'justify-between' => $between,
    'justify-end' => $right,
    'p-6' => $padded,
    
    'col-span-12' => true,
                    
    'sm:col-span-1' => $span['sm'] === 1,
    'sm:col-span-2' => $span['sm'] === 2,
    'sm:col-span-3' => $span['sm'] === 3,
    'sm:col-span-4' => $span['sm'] === 4,
    'sm:col-span-5' => $span['sm'] === 5,
    'sm:col-span-6' => $span['sm'] === 6,
    'sm:col-span-7' => $span['sm'] === 7,
    'sm:col-span-8' => $span['sm'] === 8,
    'sm:col-span-9' => $span['sm'] === 9,
    'sm:col-span-10' => $span['sm'] === 10,
    'sm:col-span-11' => $span['sm'] === 11,
    'sm:col-span-12' => $span['sm'] === 12,

    'md:col-span-1' => $span['md'] === 1,
    'md:col-span-2' => $span['md'] === 2,
    'md:col-span-3' => $span['md'] === 3,
    'md:col-span-4' => $span['md'] === 4,
    'md:col-span-5' => $span['md'] === 5,
    'md:col-span-6' => $span['md'] === 6,
    'md:col-span-7' => $span['md'] === 7,
    'md:col-span-8' => $span['md'] === 8,
    'md:col-span-9' => $span['md'] === 9,
    'md:col-span-10' => $span['md'] === 10,
    'md:col-span-11' => $span['md'] === 11,
    'md:col-span-12' => $span['md'] === 12,

    'lg:col-span-1' => $span['lg'] === 1,
    'lg:col-span-2' => $span['lg'] === 2,
    'lg:col-span-3' => $span['lg'] === 3,
    'lg:col-span-4' => $span['lg'] === 4,
    'lg:col-span-5' => $span['lg'] === 5,
    'lg:col-span-6' => $span['lg'] === 6,
    'lg:col-span-7' => $span['lg'] === 7,
    'lg:col-span-8' => $span['lg'] === 8,
    'lg:col-span-9' => $span['lg'] === 9,
    'lg:col-span-10' => $span['lg'] === 10,
    'lg:col-span-11' => $span['lg'] === 11,
    'lg:col-span-12' => $span['lg'] === 12,

    'xl:col-span-1' => $span['xl'] === 1,
    'xl:col-span-2' => $span['xl'] === 2,
    'xl:col-span-3' => $span['xl'] === 3,
    'xl:col-span-4' => $span['xl'] === 4,
    'xl:col-span-5' => $span['xl'] === 5,
    'xl:col-span-6' => $span['xl'] === 6,
    'xl:col-span-7' => $span['xl'] === 7,
    'xl:col-span-8' => $span['xl'] === 8,
    'xl:col-span-9' => $span['xl'] === 9,
    'xl:col-span-10' => $span['xl'] === 10,
    'xl:col-span-11' => $span['xl'] === 11,
    'xl:col-span-12' => $span['xl'] === 12,

    '2xl:col-span-1' => $span['2xl'] === 1,
    '2xl:col-span-2' => $span['2xl'] === 2,
    '2xl:col-span-3' => $span['2xl'] === 3,
    '2xl:col-span-4' => $span['2xl'] === 4,
    '2xl:col-span-5' => $span['2xl'] === 5,
    '2xl:col-span-6' => $span['2xl'] === 6,
    '2xl:col-span-7' => $span['2xl'] === 7,
    '2xl:col-span-8' => $span['2xl'] === 8,
    '2xl:col-span-9' => $span['2xl'] === 9,
    '2xl:col-span-10' => $span['2xl'] === 10,
    '2xl:col-span-11' => $span['2xl'] === 11,
    '2xl:col-span-12' => $span['2xl'] === 12,
])>
    @foreach ($items as $item)
        {{ $item->html() }}
    @endforeach

    {{ $text }}
</{{ $el }}>